# Generated by Django 2.2 on 2022-04-26 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_field', models.CharField(max_length=5)),
                ('name_field', models.CharField(max_length=200)),
                ('sector_field', models.CharField(max_length=200)),
                ('currency_field', models.CharField(max_length=25)),
                ('price_field', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('price_bought_field', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date_bought_field', models.DateField(default=datetime.date.today)),
                ('shares_field', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_field', models.CharField(max_length=5)),
                ('name_field', models.CharField(max_length=200)),
                ('sector_field', models.CharField(max_length=200)),
                ('currency_field', models.CharField(max_length=25)),
                ('price_field', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('price_bought_field', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date_bought_field', models.DateField(default=datetime.date.today)),
                ('shares_field', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_field', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
        ),
    ]
