# Generated by Django 2.2 on 2022-04-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_field', models.CharField(max_length=5)),
                ('date_bought_field', models.DateField()),
                ('price_bought_field', models.DecimalField(decimal_places=2, max_digits=50)),
                ('shares_field', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_field', models.IntegerField()),
            ],
        ),
    ]
