# Generated by Django 2.2 on 2022-04-26 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buymodel',
            name='price_bought_field',
        ),
        migrations.RemoveField(
            model_name='buymodel',
            name='shares_field',
        ),
    ]
