# Generated by Django 2.2 on 2022-04-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220425_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='price_field',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
