# Generated by Django 2.2 on 2022-04-24 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_stockmodel_gain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmodel',
            name='gain',
        ),
    ]
