# Generated by Django 2.2 on 2022-04-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220425_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='symbol_field',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
