# Generated by Django 2.2 on 2022-04-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_stockmodel_gain'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
