# Generated by Django 2.2 on 2022-04-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220427_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buymodel',
            name='date_bought_field',
        ),
        migrations.RemoveField(
            model_name='stockmodel',
            name='date_bought_field',
        ),
    ]
