# Generated by Django 2.2 on 2022-04-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220424_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmodel',
            name='money_field',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
